manifest: '/data/project/dohoon/workbench/snakemake-bismark-methyldackel/manifest.csv'
data_dir: '/data/project/dohoon/workbench/snakemake-bismark-methyldackel/data'
result_dir: '/data/project/dohoon/workbench/snakemake-bismark-methyldackel/result'
reference:
    name: 'hg38'
    prefix: '/data/project/dohoon/reference/hg38/hg38'
    dir: '/data/project/dohoon/reference/hg38'
    fasta: '/data/project/dohoon/reference/hg38/hg38.fa'
threads:
    trim_galore_se: 8
    trim_galore_pe: 8
    bismark_genome_preparation: 8
    bismark_se: 12 
    bismark_pe: 12 
    sambamba_sort_se: 6
    sambamba_sort_pe: 6
    sambamba_index_se: 6
    sambamba_index_pe: 6
    methyldackel_extract_se: 4
    methyldackel_extract_pe: 4
sambamba_sort_se:
    extra: ''
    memory_limit: False
    tmpdir: False
    sort_by_name: False
    compression_level: False
    uncompressed_chunks: False
    show_progress: False
sambamba_sort_pe:
    extra: ''
    memory_limit: False
    tmpdir: False
    sort_by_name: False
    compression_level: False
    uncompressed_chunks: False
    show_progress: False
bismark_genome_preparation:
    extra: ''
    verbose: False
    path_to_aligner: False
    bowtie2: True
    hisat2: False
    single_fasta: False
    genomic_composition: False
    slam: False
    large_index: False
trim_galore_se:
    extra: ''
    quality: 20
    phred33: True
    phred64: False
    fastqc: False
    fastqc_args: False
    adapter: False
    adapter2: False
    illumina: False
    nextera: False
    small_rna: False
    max_length: False
    stringency: 1
    e: 0.1
    length: 20
    max_n: False
    trim_n: False
    no_report_file: False
    suppress_warn: False
    clip_R1: False
    clip_R2: False
    three_prime_clip_R1: False
    three_prime_clip_R2: False
    nextseq: False
    basename: False
    rrbs: False
    non_directional: False
    keep: False
    trim1: False
    retain_unpaired: False
    length_1: False
    length_2: False
trim_galore_pe:
    extra: ''
    quality: 20
    phred33: True
    phred64: False
    fastqc: False
    fastqc_args: False
    adapter: False
    adapter2: False
    illumina: False
    nextera: False
    small_rna: False
    max_length: False
    stringency: 1
    e: 0.1
    length: 20
    max_n: False
    trim_n: False
    no_report_file: False
    suppress_warn: False
    clip_R1: False
    clip_R2: False
    three_prime_clip_R1: False
    three_prime_clip_R2: False
    nextseq: False
    basename: False
    rrbs: False
    non_directional: False
    keep: False
    trim1: False
    retain_unpaired: False
    length_1: False
    length_2: False
bismark_se:
    extra: ''
    single_end: False
    fastq: True
    fasta: False
    skip: False
    upto: False
    phred33_quals: True
    phred64_quals: False
    path_to_bowtie2: False
    path_to_hisat2: False
    N: 0
    L: False
    ignore_quals: False
    minins: False
    maxins: False
    local: False
    non_directional: False
    pbat: False
    sam_no_hd: False
    rg_tag: False
    rg_id: False
    rg_sample: False
    unmapped: False
    ambiguous: False
    temp_dir: False
    non_bs_mm: False
    gzip: False
    sam: False
    cram: False
    cram_ref: False
    samtools_path: False
    prefix: False
    basename: False
    old_flag: False
    ambig_bam: False
    nucleotide_coverage: False
    icpc: False
bismark_pe:
    extra: ''
    single_end: False
    fastq: True
    fasta: False
    skip: False
    upto: False
    phred33_quals: True
    phred64_quals: False
    path_to_bowtie2: False
    path_to_hisat2: False
    N: 0
    L: False
    ignore_quals: False
    minins: 0
    maxins: 500
    local: False
    non_directional: False
    pbat: False
    sam_no_hd: False
    rg_tag: False
    rg_id: False
    rg_sample: False
    unmapped: False
    ambiguous: False
    temp_dir: False
    non_bs_mm: False
    gzip: False
    sam: False
    cram: False
    cram_ref: False
    samtools_path: False
    prefix: False
    basename: False
    old_flag: False
    ambig_bam: False
    nucleotide_coverage: False
    icpc: False
methyldackel_extract_se:
    extra: ''
    q: 10
    p: 5
    D: 2000
    d: 1
    r: False
    l: False
    keepStrand: False
    chunkSize: 1000000
    mergeContext: False
    keepDupes: False
    keepSingleton: False
    keepDiscordant: False
    ignoreFlags: False
    requireFlags: False
    noCpG: False
    CHG: False
    CHH: False
    minOppositeDepth: False
    maxVariantFrac: False
    methylKit: False
    cytosine_report: False
    OT: False
    OB: False
    CTOT: False
    CTOB: False
    nOT: False
    nOB: False
    nCTOT: False
    nCTOB: False
    min_depth: 10
    mapping_quality_threshold: 10
    sequencing_quality_threshold: 5
methyldackel_extract_pe:
    extra: ''
    q: 10
    p: 5
    D: 2000
    d: 1
    r: False
    l: False
    keepStrand: False
    chunkSize: 1000000
    mergeContext: False
    opref: False
    keepDupes: False
    keepSingleton: False
    keepDiscordant: False
    ignoreFlags: False
    requireFlags: False
    noCpG: False
    CHG: False
    CHH: False
    minOppositeDepth: False
    maxVariantFrac: False
    methylKit: False
    cytosine_report: False
    OT: False
    OB: False
    CTOT: False
    CTOB: False
    nOT: False
    nOB: False
    nCTOT: False
    nCTOB: False
