name: bismark-methyldackel
channels:
    - conda-forge
    - bioconda
    - defaults
dependencies:
    - snakemake=0.6.8
    - bismark
    - methyldackel
    - trim-galore
    - sambamba
    - ldc=1.11.0
