name: bismark-methyldackel
channels:
    - conda-forge
    - bioconda
    - defaults
dependencies:
    - python=3.6
    - pandas

    - bismark=0.22.3
    - methyldackel=0.4.0
    - trim-galore
    - sambamba=0.6.8
    - ldc=1.11.0

    - pip
    - pip:
        - snakemake==5.8.2
