name: bismark-methyldackel
channels:
    - conda-forge
    - bioconda
    - defaults
dependencies:
    - snakemake
    - bismark
    - methyldackel=0.4.0
    - trim-galore
    - sambamba=0.6.8
    - ldc=1.11.0
